packages:
  - apps/*
  - shared
  - mocks
allowBuilds:
  '@firebase/util': true
  '@google/genai': false
  esbuild: true
  protobufjs: true
  unrs-resolver: true
autoDedupe: true
saveTypes: true
peerDependencyRules:
  allowedVersions:
    # suppress peer warnings from lit about @types/node
    "@lit-labs/ssr>@types/node": ">=20"
lockfile:
  includeResolutionSettings: true
